(deftheme my-adwaita
  "Created 2024-12-20.")

(defconst my-adwaita-colors
  '((blue-1 . "#99C1F1")
    (blue-2 . "#62A0EA")
    (blue-3 . "#3584E4")
    (blue-4 . "#1C71D8")
    (blue-5 . "#1A5FB4")
    (blue-6 . "#1B497E")
    (blue-7 . "#193D66")
    (brown-1 . "#CDAB8F")
    (brown-2 . "#B5835A")
    (brown-3 . "#986A44")
    (brown-4 . "#865E3C")
    (brown-5 . "#63452C")
    (chameleon-3 . "#4E9A06")
    (shade-1 . "#77767B")
    (shade-2 . "#5E5C64")
    (shade-3 . "#504E55")
    (shade-4 . "#3D3846")
    (shade-5 . "#241F31")
    (shade-6 . "#000000")
    (dark_1 . "#777777")
    (dark_2 . "#5E5E5E")
    (dark_3 . "#505050")
    (dark_4 . "#3D3D3D")
    (dark_5 . "#242424")
    (dark_6 . "#121212")
    (dark_7 . "#000000")
    (green-1 . "#8FF0A4")
    (green-2 . "#57E389")
    (green-3 . "#33D17A")
    (green-4 . "#2EC27E")
    (green-5 . "#26A269")
    (green-6 . "#1F7F56")
    (green-7 . "#1C6849")
    (light-1 . "#FFFFFF")
    (light-2 . "#FCFCFC")
    (light-3 . "#F6F5F4")
    (light-4 . "#F1F1F1")
    (light-5 . "#DEDDDA")
    (light-6 . "#C0BFBC")
    (light-7 . "#B0AFAC")
    (light-8 . "#9A9996")
    (orange-1 . "#FFBE6F")
    (orange-2 . "#FFA348")
    (orange-3 . "#FF7800")
    (orange-4 . "#E66100")
    (orange-5 . "#C64600")
    (purple-1 . "#DC8ADD")
    (purple-2 . "#C061CB")
    (purple-3 . "#9141AC")
    (purple-4 . "#813D9C")
    (purple-5 . "#613583")
    (red-1 . "#F66151")
    (red-2 . "#ED333B")
    (red-3 . "#E01B24")
    (red-4 . "#C01C28")
    (red-5 . "#A51D2D")
    (teal-1 . "#93DDC2")
    (teal-2 . "#5BC8AF")
    (teal-3 . "#33B2A4")
    (teal-4 . "#26A1A2")
    (teal-5 . "#218787")
    (violet-2 . "#7D8AC7")
    (violet-3 . "#6362C8")
    (violet-4 . "#4E57BA")
    (yellow-1 . "#F9F06B")
    (yellow-2 . "#F8E45C")
    (yellow-3 . "#F6D32D")
    (yellow-4 . "#F5C211")
    (yellow-5 . "#E5A50A")
    (yellow-6 . "#D38B09")
    (libadwaita-dark . "#1E1E1E")
    (libadwaita-dark-alt . "#202020")))

(let-alist my-adwaita-colors
 (custom-theme-set-faces
  'my-adwaita
  `(ansi-color-black ((t (:background "#1E1E1E" :foreground "#1E1E1E"))))
  `(ansi-color-blue ((t (:background "#12488B" :foreground "#12488B"))))
  `(ansi-color-bright-black ((t (:background "#5D5D5D" :foreground "#5D5D5D"))))
  `(ansi-color-bright-blue ((t (:background "#2A7BDE" :foreground "#2A7BDE"))))
  `(ansi-color-bright-cyan ((t (:background "#33C7DE" :foreground "#33C7DE"))))
  `(ansi-color-bright-green ((t (:background "#33D17A" :foreground "#33D17A"))))
  `(ansi-color-bright-magenta ((t (:background "#C061CB" :foreground "#C061CB"))))
  `(ansi-color-bright-red ((t (:background "#F66151" :foreground "#F66151"))))
  `(ansi-color-bright-yellow ((t (:background "#E9AD0C" :foreground "#E9AD0C"))))
  `(ansi-color-cyan ((t (:background "#2AA1B3" :foreground "#2AA1B3"))))
  `(ansi-color-green ((t (:background "#26A269" :foreground "#26A269"))))
  `(ansi-color-magenta ((t (:background "#A347BA" :foreground "#A347BA"))))
  `(ansi-color-red ((t (:background "#C01C28" :foreground "#C01C28"))))
  `(ansi-color-white ((t (:background "#CFCFCF" :foreground "#CFCFCF"))))
  `(ansi-color-yellow ((t (:background "#A2734C" :foreground "#A2734C"))))
  `(compilation-mode-line-fail ((t (:inherit compilation-error :weight bold))))
  `(default ((((background light)) :background ,.light-1 :foreground ,.shade-6)
	     (((background dark)) :background ,.dark-7 :foreground ,.light-1)))
  `(cursor ((t (:background ,.shade-1))))
  `(diff-added ((t (:foreground ,.teal-4))))
  `(diff-changed ((t (:foreground ,.orange-4))))
  `(diff-error ((t (:inherit error))))
  `(diff-file-header ((t (:weight bold))))
  `(diff-header ((t (:foreground ,.violet-4))))
  `(diff-hunk-header ((t (:foreground ,.yellow-6))))
  `(diff-indicator-added ((t (:inherit diff-added))))
  `(diff-indicator-changed ((t (:inherit diff-changed))))
  `(diff-indicator-removed ((t (:inherit diff-removed))))
  `(diff-refine-added ((t (:weight bold))))
  `(diff-refine-changed ((t (:weight bold))))
  `(diff-refine-removed ((t (:inherit diff-refine-changed :weight bold))))
  `(diff-removed ((t (:foreground ,.red-1))))
  `(doom-modeline-bar-inactive ((t (:background ,.light-4))))
  `(elisp-shorthand-font-lock-face ((t (:inherit font-lock-keyword-face))))
  `(error ((t (:foreground ,.red-4 :weight bold))))
  `(flymake-error ((t (:underline (:color ,.red-4 :style wave :position nil)))))
  `(flymake-warning ((t (:underline (:color ,.yellow-4 :style wave :position nil)))))
  `(font-lock-builtin-face ((t (:foreground ,.blue-4))))
  `(font-lock-comment-face ((t (:foreground ,.shade-1))))
  `(font-lock-constant-face ((t (:foreground ,.violet-4))))
  `(font-lock-function-call-face ((t (:foreground ,.blue-4))))
  `(font-lock-function-name-face ((t (:foreground ,.blue-4 :weight bold))))
  `(font-lock-keyword-face ((t (:foreground ,.orange-5 :weight bold))))
  `(font-lock-number-face ((t (:foreground ,.violet-4))))
  `(font-lock-preprocessor-face ((t (:foreground ,.orange-5))))
  `(font-lock-string-face ((t (:foreground ,.teal-5))))
  `(font-lock-type-face ((t (:foreground ,.teal-5 :weight bold))))
  `(font-lock-variable-name-face ((t nil)))
  `(fringe ((t :background ,.light-1)))
  `(header-line ((t (:inherit variable-pitch :background ,.light-4 :box (:line-width (4 . 4) :style flat-button)))))
  `(header-line-highlight ((t :box (:color ,.shade-3))))
  `(highlight ((t (:background ,.light-3))))
  `(hl-line ((t (:inherit (highlight default) :extend t))))
  `(isearch ((t (:background ,.blue-3 :foreground ,.light-1))))
  `(keycast-key ((t)))
  `(lazy-highlight ((t (:background ,.yellow-1 :distant-foreground "black"))))
  `(line-number ((t (:inherit (shadow default)))))
  `(line-number-current-line ((t (:inherit (hl-line line-number) :weight bold))))
  `(link ((t (:foreground ,.blue-3 :underline t))))
  `(link-visited ((t (:inherit link :foreground ,.purple-4))))
  `(markdown-header-face ((t (:foreground ,.teal-5 :weight bold))))
  `(markdown-list-face ((t (:foreground ,.orange-5 :weight bold))))
  `(minibuffer-prompt ((t (:inherit default :weight bold))))
  `(mode-line-highlight ((t (:foreground ,.light-8))))
  `(orderless-match-face-0 ((t (:foreground "#8939A4"))))
  `(orderless-match-face-1 ((t (:inherit orderless-match-face-0))))
  `(orderless-match-face-2 ((t (:inherit orderless-match-face-0))))
  `(orderless-match-face-3 ((t (:inherit orderless-match-face-2))))
  `(org-mode-line-clock-overrun ((t (:inherit error))))
  `(region ((t (:extend t :background "#DEC6E6"))))
  `(tab-line-tab ((t)))
  `(tab-line-tab-active ((t)))
  `(tab-line-tab-inactive ((t)))
  `(trailing-whitespace ((t (:foreground ,.light-7))))
  `(vertical-border ((((background light)) :background ,.light-1 :foreground ,.light-1)
		     (((background dark)) :background "#000000" :foreground "#000000")))
  `(vertico-current ((t (:inherit hl-line :extend t :weight bold))))))

(provide-theme 'my-adwaita)
